version: '3.9'

services:
  data-porter.api:
    container_name: "data-porter.api"
    hostname: "data-porter.api"
    image: ${DOCKER_REGISTRY-}dataporterapi
    build:
      context: .
      dockerfile: data-porter.Api/data-porter.Api/Dockerfile
