version: '3.9'

services:
  data-porter.api:
    container_name: "data-porter.api"
    hostname: "data-porter.api"
    image: ${DOCKER_REGISTRY-}dataporterapi
    build:
      context: .
      dockerfile: data-porter.Api/data-porter.Api/Dockerfile

  data-porter.db:
    container_name: "data-porter.db"
    hostname: "data-porter.db"
    image: postgres:${POSTGRES_VERSION:-latest}
    ports:
      - "5438:5432"
    env_file:
      - env/.postgres-env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    driver: local
